import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >

        <h2 className={"centered"}>BEM VINDA MAMA!</h2>
        <h2 className={"centered"}>AQUI VOCÊ TEM ACESSO A TODAS AS SEASONS LANÇADAS E FUTURAS</h2>

        <div className={styles.grid} >
          <Link href="/seasons/season1">
            <a style={{ fontSize: "50px", "color": "blue" }}>
              SEASON 1
            </a>
          </Link>
        </div>
        <div className={styles.grid}>
          <Link href="/seasons/season1">
            <a style={{ fontSize: "50px", color: "lightgray", pointerEvents: 'none' }}>
              SEASON 2
            </a>
          </Link>
        </div>


      </main>

      <footer className={styles.footer}>
        <Image id="i" alt="" width="100%" height="100%" src="/woody.jpg" />
      </footer>
    </div>
  )
}
